#!/bin/bash
#SBATCH --job-name=gaussian-grouping
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --mem=64G
#SBATCH --time=04:00:00
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err

# Usage:
#   sbatch script/snellius_train.job <dataset_name> <scale>
# Example:
#   sbatch script/snellius_train.job figurines 1

DATASET_NAME=${1:?"Usage: sbatch snellius_train.job <dataset_name> <scale>"}
SCALE=${2:-1}
DATASET_FOLDER=data/$DATASET_NAME
OUTPUT_DIR=output/${DATASET_NAME}

echo "Dataset : $DATASET_FOLDER"
echo "Output  : $OUTPUT_DIR"
echo "Node    : $(hostname)"
echo "GPU     : $(nvidia-smi --query-gpu=name --format=csv,noheader)"

module purge
module load 2023
module load CUDA/12.1.1
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/gaussian-grouping/.venv_snellius/bin/activate

mkdir -p logs

python train.py \
    -s $DATASET_FOLDER \
    -m $OUTPUT_DIR \
    -r $SCALE \
    --config_file config_with_boundary.json

python render.py \
    -m $OUTPUT_DIR
